#ifndef _ASD_COMPONENTS_CONTINUOUSTRACK_AUTOMATIC_H_
#define _ASD_COMPONENTS_CONTINUOUSTRACK_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ContinuousTrack_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:03:20
*
* @brief   "components_ContinuousTrack>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_ContinuousTrack_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct components_ContinuousTrack_Automatic_RAM_SUBSTRUCT {
   float32 totalDistance;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'components_ContinuousTrack_Automatic'
 ******************************************************************************/


/* component structure for module COMPONENTS_CONTINUOUSTRACK_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .......components_ContinuousTrack_Automatic */
#define _components_ContinuousTrack_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'components_ContinuousTrack_RAM' */
/* containing 'RAM' memory class tree */
extern struct components_ContinuousTrack_Automatic_RAM_SUBSTRUCT components_ContinuousTrack_RAM;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module components_ContinuousTrack_Automatic
 ******************************************************************************/
extern float32 components_ContinuousTrack_Automatic_getTotalDistance (void);
extern float32 components_ContinuousTrack_Automatic_getTrackPosition (
   /* IN    */ const float32 position,
   /* IN    */ const float32 ds,
   /* IN    */ const float32 trackSize
   );



#endif /* _ASD_COMPONENTS_CONTINUOUSTRACK_AUTOMATIC_H_ */
