/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_Component_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:03:20
*
* @brief   "components_Component>>Automatic (module code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_Component_Automatic.h"
#include "ESDL_Linear_Interpolation.h"
/******************************************************************************
 * BEGIN: source code of a multiple instance class
 ******************************************************************************/



/******************************************************************************
 * BEGIN: DEFINITION OF CHARACTERISTIC TABLE 'components_Component_Landscape'
 * ---------------------------------------------------------------------------*/
const volatile struct CharTable1_real32_20_real32_TYPE components_Component_Landscape = {
      20U,
      {
         0.0F, 100.0F, 145.569620253165F, 202.53164556962F, 221.518987341772F, 240.0F,
         259.493670886076F, 300.0F, 350.0F, 400.0F, 450.0F, 500.0F, 600.0F, 700.0F,
         750.0F, 800.0F, 810.0F, 850.0F, 900.0F, 1000.0F
      },
      {
         0.0F, 4.0F, 7.125F, 10.375F, 10.75F, 10.5F, 9.0F, 5.375F, 2.625F, 0.625F, 1.25F,
         0.625F, 0.0F, 0.0F, 1.375F, 0.75F, 0.375F, 0.625F, 0.0F, 0.0F
      }
   };
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF CHARACTERISTIC TABLE 'components_Component_Landscape'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_calc'
 * ----------------------------------------------------------------------------
 * model name:...................................'calc'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void components_Component_Automatic_calc (
               const struct components_Component_Automatic * self,
   /* IN    */ const float32                                 brake,
   /* IN    */ const float32                                 power,
   /* IN    */ const float32                                 dtime
   )
{
   self->components_Component_Automatic_RAM->ds = (self->components_Component_Automatic_RAM->v * dtime) / 3.6F;
   self->components_Component_Automatic_RAM->dh
      = self->components_Component_Automatic_RAM->h - ESDL_Linear_CharTable1_getAt_r32r32(((&(components_Component_Landscape)))->xSize, ((&(components_Component_Landscape)))->xDist, ((&(components_Component_Landscape)))->values, self->components_Component_Automatic_RAM->s);
   self->components_Component_Automatic_RAM->h
      = ESDL_Linear_CharTable1_getAt_r32r32(((&(components_Component_Landscape)))->xSize, ((&(components_Component_Landscape)))->xDist, ((&(components_Component_Landscape)))->values, self->components_Component_Automatic_RAM->s);
   self->components_Component_Automatic_RAM->momentum
      = ESDL_Linear_CharTable2_getAt_r32r32r32(((&(self->components_Component_Automatic_CAL_MEM->EngineMomentum)))->xSize, ((&(self->components_Component_Automatic_CAL_MEM->EngineMomentum)))->xDist, ((&(self->components_Component_Automatic_CAL_MEM->EngineMomentum)))->ySize, ((&(self->components_Component_Automatic_CAL_MEM->EngineMomentum)))->yDist, ((&(self->components_Component_Automatic_CAL_MEM->EngineMomentum)))->values, power, self->components_Component_Automatic_RAM->v);
   self->components_Component_Automatic_RAM->v
      = ((ESDL_Linear_CharTable1_getAt_r32r32(((&(self->components_Component_Automatic_CAL_MEM->BrakeMomentum)))->xSize, ((&(self->components_Component_Automatic_CAL_MEM->BrakeMomentum)))->xDist, ((&(self->components_Component_Automatic_CAL_MEM->BrakeMomentum)))->values, brake) + self->components_Component_Automatic_RAM->momentum + ESDL_Linear_CharTable1_getAt_r32r32(((&(self->components_Component_Automatic_CAL_MEM->AirFriction)))->xSize, ((&(self->components_Component_Automatic_CAL_MEM->AirFriction)))->xDist, ((&(self->components_Component_Automatic_CAL_MEM->AirFriction)))->values, self->components_Component_Automatic_RAM->v) + ((((self->components_Component_Automatic_RAM->ds == 0.0F) ? self->components_Component_Automatic_RAM->dh : (self->components_Component_Automatic_RAM->dh / self->components_Component_Automatic_RAM->ds))) * 9.81F)) * dtime * 3.6F) + self->components_Component_Automatic_RAM->v;
   self->components_Component_Automatic_RAM->s
      = self->components_Component_Automatic_RAM->ds + self->components_Component_Automatic_RAM->s;
   if (self->components_Component_Automatic_RAM->s > self->components_Component_Automatic_CAL_MEM->TrackSize)
   {
      self->components_Component_Automatic_RAM->s = 0.0F;
   } /* end if */
   if (self->components_Component_Automatic_RAM->v < 0.0F)
   {
      self->components_Component_Automatic_RAM->v = 0.0F;
   } /* end if */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_calc'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_get_dh'
 * ----------------------------------------------------------------------------
 * model name:...................................'get_dh'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_get_dh ( const struct components_Component_Automatic * self)
{
   return self->components_Component_Automatic_RAM->dh;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_get_dh'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_get_ds'
 * ----------------------------------------------------------------------------
 * model name:...................................'get_ds'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_get_ds ( const struct components_Component_Automatic * self)
{
   return self->components_Component_Automatic_RAM->ds;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_get_ds'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_get_v'
 * ----------------------------------------------------------------------------
 * model name:...................................'get_v'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_get_v ( const struct components_Component_Automatic * self)
{
   return self->components_Component_Automatic_RAM->v;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_get_v'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_getPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'getPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_getPosition ( const struct components_Component_Automatic * self)
{
   return self->components_Component_Automatic_RAM->s;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_getPosition'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_Component_Automatic_getTracksize'
 * ----------------------------------------------------------------------------
 * model name:...................................'getTracksize'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_Component_Automatic_getTracksize ( const struct components_Component_Automatic * self)
{
   return self->components_Component_Automatic_CAL_MEM->TrackSize;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_Component_Automatic_getTracksize'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



