/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    components_ContinuousTrack_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:03:20
*
* @brief   "components_ContinuousTrack>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "components_ContinuousTrack_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'components_ContinuousTrack_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'components_ContinuousTrack'
 * data set:.....................................'COMPONENTS_CONTINUOUSTRACK_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct components_ContinuousTrack_Automatic_RAM_SUBSTRUCT components_ContinuousTrack_RAM = {
   /* struct element:'components_ContinuousTrack_RAM.totalDistance' (modeled as:'totalDistance.components_ContinuousTrack') */
   0.0F
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'components_ContinuousTrack_RAM'
 ******************************************************************************/

/******************************************************************************
 * DEFINITION OF COMPONENT VARIABLE OMITTED
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'components_ContinuousTrack'
 * reason:.......................................no local elements
 * ---------------------------------------------------------------------------*/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ContinuousTrack_Automatic_getTotalDistance'
 * ----------------------------------------------------------------------------
 * model name:...................................'getTotalDistance'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_ContinuousTrack_Automatic_getTotalDistance (void)
{
   return components_ContinuousTrack_RAM.totalDistance;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ContinuousTrack_Automatic_getTotalDistance'
 ******************************************************************************/




/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'components_ContinuousTrack_Automatic_getTrackPosition'
 * ----------------------------------------------------------------------------
 * model name:...................................'getTrackPosition'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

float32 components_ContinuousTrack_Automatic_getTrackPosition (
   /* IN    */ const float32 position,
   /* IN    */ const float32 ds,
   /* IN    */ const float32 trackSize
   )
{
   /* temp. variables */
   float32 _t1real32;

   components_ContinuousTrack_RAM.totalDistance = components_ContinuousTrack_RAM.totalDistance + ds;
   _t1real32 = position + ds;
   if (_t1real32 > trackSize)
   {
      return _t1real32 - trackSize;
   } /* end if */
   if (_t1real32 < 0.0F)
   {
      return (trackSize - position) + ds;
   } /* end if */
   return _t1real32;
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'components_ContinuousTrack_Automatic_getTrackPosition'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



