#ifndef _ASD_GRAPH_PROGR_AUTOMATIC_H_
#define _ASD_GRAPH_PROGR_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    Graph_Progr_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:03:20
*
* @brief   "Graph_Progr>>Automatic (project code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "assertLib_Assert_Impl.h"
#include "components_ContinuousTrack_Automatic.h"
#include "tests_SlopeTests_Automatic.h"


/* component structure for project GRAPH_PROGR_AUTOMATIC intentionally not created */
/* reason: no local elements                                                  */

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: ......................Graph_Progr_Automatic */
#define _Graph_Progr_Automatic_TYPE_DEF_



/******************************************************************************
 * BEGIN: declaration of global C variables exported by project Graph_Progr_Automatic
 ******************************************************************************/



#endif /* _ASD_GRAPH_PROGR_AUTOMATIC_H_ */
