#ifndef _ASD_TESTS_SLOPETESTS_AUTOMATIC_H_
#define _ASD_TESTS_SLOPETESTS_AUTOMATIC_H_
/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    tests_SlopeTests_Automatic.h
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:03:20
*
* @brief   "tests_SlopeTests>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/


/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "esdl.h"
#include "chartab.h"
#include "components_Component_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'tests_SlopeTests_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * ---------------------------------------------------------------------------*/
struct tests_SlopeTests_Automatic_CAL_MEM_SUBSTRUCT {
   float32 TrackSize;
   struct components_Component_Automatic_CAL_MEM_SUBSTRUCT Comp;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'tests_SlopeTests_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'tests_SlopeTests_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * ---------------------------------------------------------------------------*/
struct tests_SlopeTests_Automatic_RAM_SUBSTRUCT {
   float32 dh;
   float32 ds;
   float32 s;
   float32 totaldist;
   struct components_Component_Automatic_RAM_SUBSTRUCT Comp;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MEMORY CLASS STRUCTURE FOR MODULE 'tests_SlopeTests_Automatic'
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF MAIN STRUCTURE FOR MODULE 'tests_SlopeTests_Automatic'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * ---------------------------------------------------------------------------*/
struct tests_SlopeTests_Automatic {
   struct components_Component_Automatic Comp;
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF MAIN STRUCTURE FOR MODULE 'tests_SlopeTests_Automatic'
 ******************************************************************************/

/* Following DEFINE signalizes the completion of definition                   */
/* of data structs for component: .................tests_SlopeTests_Automatic */
#define _tests_SlopeTests_Automatic_TYPE_DEF_




/* forward declaration of substruct variable 'tests_SlopeTests_CAL_MEM' */
/* containing 'CAL_MEM' memory class tree */
extern const volatile struct tests_SlopeTests_Automatic_CAL_MEM_SUBSTRUCT tests_SlopeTests_CAL_MEM;

/* forward declaration of substruct variable 'tests_SlopeTests_RAM' */
/* containing 'RAM' memory class tree */
extern struct tests_SlopeTests_Automatic_RAM_SUBSTRUCT tests_SlopeTests_RAM;

/* forward declaration of component variable 'tests_SlopeTests' */
/* containing 'ROM' memory class tree */
extern const struct tests_SlopeTests_Automatic tests_SlopeTests;

/******************************************************************************
 * BEGIN: declaration of global C functions defined by module tests_SlopeTests_Automatic
 ******************************************************************************/
extern void tests_SlopeTests_Automatic_testSlopeLimit (void);



#endif /* _ASD_TESTS_SLOPETESTS_AUTOMATIC_H_ */
