/**
* @warning AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
*
* @file    tests_SlopeTests_Automatic.c
*
* @author  Generated by ASCET-DEVELOPER V7.4.0 (Backend: Code Generator V7.4.0)
*
* @date    05.03.2019 13:03:20
*
* @brief   "tests_SlopeTests>>Automatic (>>esdl_Data_Default combined module/init code)"
*
*/



/*-----------------------------------------------------------------------------
 *    Include files
 *----------------------------------------------------------------------------*/

#include "globalH.h"
#include "tests_SlopeTests_Automatic.h"
#include "assertLib_Assert_Impl.h"
#include "components_ContinuousTrack_Automatic.h"
#include "Graph_Progr_Automatic.h"


/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'tests_SlopeTests_CAL_MEM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'CAL_MEM'
 * model name:...................................'tests_SlopeTests'
 * data set:.....................................'TESTS_SLOPETESTS_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const volatile struct tests_SlopeTests_Automatic_CAL_MEM_SUBSTRUCT tests_SlopeTests_CAL_MEM = {
   /* struct element:'tests_SlopeTests_CAL_MEM.TrackSize' (modeled as:'TrackSize.tests_SlopeTests') */
   1000.0F,
   /* substruct: tests_SlopeTests_CAL_MEM.Comp (modeled as:'Comp.tests_SlopeTests') */
   {
      /* struct element:'tests_SlopeTests_CAL_MEM.Comp.TrackSize' (modeled as:'TrackSize.Comp.tests_SlopeTests') */
      1000.0F,
      /* struct element:'tests_SlopeTests_CAL_MEM.Comp.AirFriction' (modeled as:'AirFriction.Comp.tests_SlopeTests') */
      {
         6U,
         {
            0.0F, 30.0F, 60.0F, 90.0F, 120.0F, 150.0F
         },
         {
            0.0F, -0.1F, -0.2F, -0.4F, -0.8F, -1.6F
         }
      },
      /* struct element:'tests_SlopeTests_CAL_MEM.Comp.BrakeMomentum' (modeled as:'BrakeMomentum.Comp.tests_SlopeTests') */
      {
         6U,
         {
            0.0F, 1.0F, 40.0F, 60.0F, 80.0F, 100.0F
         },
         {
            0.0F, 0.0F, -1.0F, -2.0F, -3.0F, -4.0F
         }
      },
      /* struct element:'tests_SlopeTests_CAL_MEM.Comp.EngineMomentum' (modeled as:'EngineMomentum.Comp.tests_SlopeTests') */
      {
         6U,
         6U,
         {
            0.0F, 5.0F, 20.0F, 60.126582278481F, 80.0F, 100.0F
         },
         {
            0.0F, 30.0F, 60.0F, 90.0F, 150.0F, 200.0F
         },
         {
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.0F,
            8.49999999999999e-1F, 0.6F, 0.3F, 0.0F, 0.0F, 0.0F,
            3.15F, 2.35F, 1.55F, 8.00000000000001e-1F, 3.99999999999999e-1F, 0.0F,
            4.5F, 3.6F, 2.7F, 1.5F, 0.9F, 0.0F,
            5.0F, 4.5F, 3.8F, 2.8F, 1.9F, 0.0F
         }
      }
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'tests_SlopeTests_CAL_MEM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF SUBSTRUCT VARIABLE 'tests_SlopeTests_RAM'
 * ----------------------------------------------------------------------------
 * memory class:.................................'RAM'
 * model name:...................................'tests_SlopeTests'
 * data set:.....................................'TESTS_SLOPETESTS_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
struct tests_SlopeTests_Automatic_RAM_SUBSTRUCT tests_SlopeTests_RAM = {
   /* struct element:'tests_SlopeTests_RAM.dh' (modeled as:'dh.tests_SlopeTests') */
   0.0F,
   /* struct element:'tests_SlopeTests_RAM.ds' (modeled as:'ds.tests_SlopeTests') */
   0.0F,
   /* struct element:'tests_SlopeTests_RAM.s' (modeled as:'s.tests_SlopeTests') */
   0.0F,
   /* struct element:'tests_SlopeTests_RAM.totaldist' (modeled as:'totaldist.tests_SlopeTests') */
   0.0F,
   /* substruct: tests_SlopeTests_RAM.Comp (modeled as:'Comp.tests_SlopeTests') */
   {
      /* struct element:'tests_SlopeTests_RAM.Comp.dh' (modeled as:'dh.Comp.tests_SlopeTests') */
      0.0F,
      /* struct element:'tests_SlopeTests_RAM.Comp.ds' (modeled as:'ds.Comp.tests_SlopeTests') */
      0.0F,
      /* struct element:'tests_SlopeTests_RAM.Comp.h' (modeled as:'h.Comp.tests_SlopeTests') */
      0.0F,
      /* struct element:'tests_SlopeTests_RAM.Comp.momentum' (modeled as:'momentum.Comp.tests_SlopeTests') */
      0.0F,
      /* struct element:'tests_SlopeTests_RAM.Comp.s' (modeled as:'s.Comp.tests_SlopeTests') */
      0.0F,
      /* struct element:'tests_SlopeTests_RAM.Comp.v' (modeled as:'v.Comp.tests_SlopeTests') */
      0.0F
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF SUBSTRUCT VARIABLE 'tests_SlopeTests_RAM'
 ******************************************************************************/

/******************************************************************************
 * BEGIN: DEFINITION OF COMPONENT VARIABLE 'tests_SlopeTests'
 * ----------------------------------------------------------------------------
 * memory class:.................................'ROM'
 * model name:...................................'tests_SlopeTests'
 * data set:.....................................'TESTS_SLOPETESTS_AUTOMATIC_esdl_Data_Default'
 * ---------------------------------------------------------------------------*/
const struct tests_SlopeTests_Automatic tests_SlopeTests = {
   /* substruct: tests_SlopeTests.Comp (modeled as:'Comp.tests_SlopeTests') */
   {
      /* type descriptor pointer 'components_Component_Automatic_CAL_MEM' for memory class substruct for 'CAL_MEM' */
      &tests_SlopeTests_CAL_MEM.Comp,
      /* type descriptor pointer 'components_Component_Automatic_RAM' for memory class substruct for 'RAM' */
      &tests_SlopeTests_RAM.Comp
   }
};
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF COMPONENT VARIABLE 'tests_SlopeTests'
 ******************************************************************************/







/******************************************************************************
 * BEGIN: FUNCTIONS OF COMPONENT
 ******************************************************************************/


/******************************************************************************
 * BEGIN: DEFINITION OF METHOD 'tests_SlopeTests_Automatic_testSlopeLimit'
 * ----------------------------------------------------------------------------
 * model name:...................................'testSlopeLimit'
 * memory class:.................................'CODE'
 * ---------------------------------------------------------------------------*/

void tests_SlopeTests_Automatic_testSlopeLimit (void)
{
   while (tests_SlopeTests_RAM.totaldist < (tests_SlopeTests_CAL_MEM.TrackSize * 2.0F))
   {
      components_Component_Automatic_calc(&(tests_SlopeTests.Comp), 0.0F, 100.0F, 0.01F);
      tests_SlopeTests_RAM.dh
         = components_Component_Automatic_get_dh(&(tests_SlopeTests.Comp));
      tests_SlopeTests_RAM.ds
         = components_Component_Automatic_get_ds(&(tests_SlopeTests.Comp));
      tests_SlopeTests_RAM.s
         = components_ContinuousTrack_Automatic_getTrackPosition(tests_SlopeTests_RAM.s, tests_SlopeTests_RAM.ds, tests_SlopeTests_CAL_MEM.TrackSize);
      tests_SlopeTests_RAM.totaldist = components_ContinuousTrack_Automatic_getTotalDistance();
      ASSERT_TRUE((((tests_SlopeTests_RAM.ds == 0.0F) ? tests_SlopeTests_RAM.dh : (tests_SlopeTests_RAM.dh / tests_SlopeTests_RAM.ds))) <= 0.2F);
      ASSERT_TRUE((((tests_SlopeTests_RAM.ds == 0.0F) ? tests_SlopeTests_RAM.dh : (tests_SlopeTests_RAM.dh / tests_SlopeTests_RAM.ds))) >= -0.2F);
   } /* end while */
}
/* ----------------------------------------------------------------------------
 * END: DEFINITION OF METHOD 'tests_SlopeTests_Automatic_testSlopeLimit'
 ******************************************************************************/



/* ****************************************************************************
 * END: FUNCTIONS OF COMPONENT
 ******************************************************************************/



